/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tis.poc.automated.versioned.releases;

public class App {
    public String getGreeting() {
        return "Hello World.";
    }

    public static void main(String[] args) {
        TestMagic testMagic =  new TestMagic();
        System.out.println(testMagic.magicMe("Steven Spilburg"));
        System.out.println(new App().getGreeting());
    }
}
