name: PR Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  analysis:
    name: Analyse PR
    uses: health-education-england/tis-poc-automated-versioned-releases-reusable/.github/workflows/pr-analysis-common.yml@main
