name: Auto Version

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Auto Version
    uses: health-education-england/tis-poc-automated-versioned-releases-reusable/.github/workflows/auto-version.yml@main
